PUT http://127.0.0.1:5000/users/password/1
Content-Type: application/json

{
  "password_1": "password1",
"password_2": "password2"
}
###
GET http://127.0.0.1:5000/users
###
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "email": "user1@gmail.com",
"password": "password1"
}
###
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "email": "user2@gmail.com",
"password": "password2"
}
###
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "email": "user3@yandex.ru",
"password": "password3"
}
